version: 0.0
os: linux
files:
 - source: /src
   destination: /home/ec2-user/server2
 - source: requirements.txt
   destination: /home/ec2-user/server2
permissions:
  - object: /home/ec2-user/server2/helloworld.py
    owner: ec2-user
    group: ec2-user
    type:
      - file
  - object: /home/ec2-user/server2/requirements.txt
    owner: ec2-user
    group: ec2-user
    type:
      - file
hooks:
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 300
     runas: ec2-user
   - location: scripts/start_server
     timeout: 300
     runas: ec2-user
