version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/server3
 - source: requirements.txt
permissions:
  - object: /home/ec2-user/server3/helloworld.py
    owner: ec2-user
    group: ec2-user
    type:
      - file
hooks:
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 300
     runas: ec2-user
   - location: scripts/start_server
     timeout: 300
     runas: ec2-user
