version: 0.0
os: linux
files:
 - source: /app.wsgi
    destination: /var/www/server3
  - source: /
    destination: /home/ec2-user/server3
  - source: /conf/server3.conf
    destination: /etc/httpd/conf.d
permissions:
  - object: /home/ec2-user/server3/helloworld.py
    owner: ec2-user
    group: ec2-user
    type:
      - file
  - object: /home/ec2-user/server3/requirements.txt
    owner: ec2-user
    group: ec2-user
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
